[package]
name = "rainbowtable"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
custom_error = "1.9.2"
sha3 = "0.9.1"
hex = "0.4.3"
rayon = "1.5.1"
csv = "1.1.6"
